export type Locale = 'en' | 'zh';

export type ModuleLesson = {
  slug: string;
  order: number;
  title: { en: string; zh: string };
  summary: { en: string; zh: string };
  whyItMatters: { en: string; zh: string };
  prerequisites: { en: string[]; zh: string[] };
  objectives: { en: string[]; zh: string[] };
  concepts: { en: string[]; zh: string[] };
  practice: { en: string[]; zh: string[] };
  output: { en: string; zh: string };
  commonMistakes: { en: string[]; zh: string[] };
  nextStep: { en: string; zh: string };
};

export type CourseModuleCollection = {
  courseSlug: string;
  courseTitle: { en: string; zh: string };
  intro: { en: string; zh: string };
  modules: ModuleLesson[];
};

export const COURSE_MODULES: CourseModuleCollection[] = [
  {
    courseSlug: 'pytorch-foundations',
    courseTitle: { en: 'PyTorch Foundations', zh: 'PyTorch 基础' },
    intro: {
      en: 'This track builds practical deep learning engineering habits from first principles. Learners go from tensors and autograd to full training loops, GPU usage, and a CIFAR-10 capstone.',
      zh: '这条课程主线从第一性原理建立深度学习工程习惯。学习者会从 tensor 与 autograd 走到完整训练循环、GPU 使用和 CIFAR-10 压轴项目。',
    },
    modules: [
      { slug: 'tensor-fundamentals', order: 1, title: { en: 'Tensor Fundamentals', zh: 'Tensor 基础' }, summary: { en: 'Master shape reasoning, indexing, broadcasting, and device awareness.', zh: '掌握 shape 推理、索引、broadcasting 和 device 意识。'}, whyItMatters: { en: 'Every model bug eventually becomes a tensor bug. If shapes do not make sense, nothing above them will make sense either.', zh: '几乎所有模型 bug 最后都会落到 tensor bug 上。如果 shape 不清楚，上层一切都会变得混乱。'}, prerequisites: { en: ['Basic Python syntax', 'Lists, loops, and functions'], zh: ['基础 Python 语法', '列表、循环和函数']}, objectives: { en: ['Read and predict tensor shapes before running code', 'Use reshape, permute, squeeze, unsqueeze, and broadcasting safely', 'Move tensors across CPU, MPS, and CUDA devices intentionally'], zh: ['在运行代码前就能读懂并预测 tensor shape', '安全使用 reshape、permute、squeeze、unsqueeze 与 broadcasting', '有意识地在 CPU、MPS 与 CUDA 之间迁移 tensor']}, concepts: { en: ['Shape, rank, dtype, and device', 'Contiguous vs non-contiguous tensors', 'Broadcasting rules and silent shape expansion'], zh: ['shape、rank、dtype 与 device', '连续与非连续 tensor', 'broadcasting 规则与静默 shape 扩展']}, practice: { en: ['Write a tensor workbook with 15 small exercises', 'Implement matrix multiplication using batched tensor ops', 'Trigger and debug three broadcasting mistakes on purpose'], zh: ['写一个包含 15 个小题的 tensor 练习本', '用批量 tensor 运算实现矩阵乘法', '故意制造并修复 3 个 broadcasting 错误']}, output: { en: 'A notebook that explains tensor operations with shape annotations and failure cases.', zh: '一个带 shape 注释和失败案例说明的 notebook。'}, commonMistakes: { en: ['Trusting print output instead of understanding dimensions', 'Using view on non-contiguous tensors', 'Ignoring dtype mismatches during arithmetic'], zh: ['只看 print 输出而不真正理解维度', '在非连续 tensor 上误用 view', '在运算时忽略 dtype 不匹配']}, nextStep: { en: 'Use this shape intuition to understand autograd and gradient flow.', zh: '把这套 shape 直觉带到 autograd 与梯度流中。'} },
      { slug: 'autograd-backpropagation', order: 2, title: { en: 'Autograd and Backpropagation', zh: 'Autograd 与反向传播' }, summary: { en: 'Understand computational graphs, gradient flow, and backward passes.', zh: '理解计算图、梯度流和 backward 过程。'}, whyItMatters: { en: 'Training only becomes real when you understand where gradients come from and why they disappear, explode, or accumulate.', zh: '只有理解梯度从哪里来、为什么会消失、爆炸或累积，训练这件事才真正变得可控。'}, prerequisites: { en: ['Tensor operations', 'Basic derivatives'], zh: ['tensor 运算', '基础导数概念']}, objectives: { en: ['Explain requires_grad, grad_fn, backward, and detach', 'Manually compare symbolic gradients with autograd output', 'Debug accumulation and no_grad issues'], zh: ['解释 requires_grad、grad_fn、backward 和 detach', '把手工梯度和 autograd 输出对比起来', '调试梯度累积与 no_grad 相关问题']}, concepts: { en: ['Reverse-mode automatic differentiation', 'Gradient accumulation', 'Computation graph lifetime'], zh: ['反向模式自动微分', '梯度累积', '计算图生命周期']}, practice: { en: ['Differentiate a small polynomial by hand and with PyTorch', 'Inspect grad_fn chains in a simple MLP', 'Break training with in-place ops and then fix it'], zh: ['手工与 PyTorch 两种方式求一个小多项式的导数', '查看简单 MLP 中的 grad_fn 链路', '用 in-place 操作故意破坏训练再修复']}, output: { en: 'A minimal autograd lab that demonstrates gradient flow and common failure modes.', zh: '一个展示梯度流与常见失败模式的最小 autograd 实验。'}, commonMistakes: { en: ['Forgetting zero_grad', 'Calling backward twice on a freed graph', 'Using detach where gradients are required'], zh: ['忘记 zero_grad', '在已释放的图上调用两次 backward', '在需要梯度的地方误用 detach']}, nextStep: { en: 'With gradients clear, the next move is structuring trainable models.', zh: '当梯度逻辑清楚后，下一步就是组织可训练模型结构。'} },
      { slug: 'building-with-nn-module', order: 3, title: { en: 'Building Models with nn.Module', zh: '用 nn.Module 构建模型' }, summary: { en: 'Turn loose tensor math into reusable trainable modules.', zh: '把零散 tensor 运算组织成可复用的可训练模块。'}, whyItMatters: { en: 'Real projects need code you can inspect, reuse, and extend, not one-off forward passes hidden in notebooks.', zh: '真实项目需要的是可检查、可复用、可扩展的代码，而不是藏在 notebook 里的临时 forward。'}, prerequisites: { en: ['Autograd basics', 'Python classes'], zh: ['autograd 基础', 'Python 类']}, objectives: { en: ['Register parameters and submodules correctly', 'Design clear forward methods', 'Split big models into reusable blocks'], zh: ['正确注册参数和子模块', '设计清晰的 forward 方法', '把大模型拆成可复用 block']}, concepts: { en: ['Parameter registration', 'Module composition', 'Forward semantics'], zh: ['参数注册', '模块组合', 'forward 语义']}, practice: { en: ['Implement an MLP and inspect named_parameters', 'Refactor repeated code into a reusable block', 'Count parameters and identify the largest submodule'], zh: ['实现一个 MLP 并检查 named_parameters', '把重复逻辑重构成可复用 block', '统计参数量并找出最大子模块']}, output: { en: 'A clean module-based classifier skeleton ready for training.', zh: '一个基于模块组织、可直接训练的分类器骨架。'}, commonMistakes: { en: ['Creating layers inside forward', 'Forgetting super().__init__', 'Shadowing module attributes with plain tensors'], zh: ['在 forward 里创建层', '忘记 super().__init__', '用普通 tensor 覆盖模块属性']}, nextStep: { en: 'Once models are structured, learn how loss and optimization actually move parameters.', zh: '模型结构清楚之后，就该理解损失函数和优化器怎样推动参数更新。'} },
      { slug: 'losses-optimizers-schedulers', order: 4, title: { en: 'Losses, Optimizers, and Schedulers', zh: '损失函数、优化器与调度器' }, summary: { en: 'Learn how objectives and update rules shape model behavior.', zh: '理解目标函数和更新规则如何塑造模型行为。'}, whyItMatters: { en: 'A good architecture can still fail under the wrong optimizer, learning rate, or objective.', zh: '再好的架构，如果优化器、学习率或目标函数选错，也一样会失败。'}, prerequisites: { en: ['Autograd', 'Basic probability'], zh: ['autograd', '基础概率']}, objectives: { en: ['Choose common losses correctly', 'Compare SGD, Adam, and AdamW', 'Understand warmup, cosine decay, and schedule timing'], zh: ['正确选择常见损失函数', '比较 SGD、Adam 和 AdamW', '理解 warmup、cosine decay 与调度时机']}, concepts: { en: ['Cross-entropy and regression losses', 'Adaptive optimization', 'Learning rate scheduling'], zh: ['交叉熵与回归损失', '自适应优化', '学习率调度']}, practice: { en: ['Train one model with three optimizers', 'Plot loss and learning-rate curves', 'Show one bad schedule and explain the failure'], zh: ['用三个优化器训练同一个模型', '绘制 loss 与学习率曲线', '展示一个错误调度并解释失败原因']}, output: { en: 'A short benchmark note on optimization tradeoffs for a small model.', zh: '一份关于小模型优化取舍的 benchmark 记录。'}, commonMistakes: { en: ['Confusing logits with probabilities', 'Stepping the scheduler at the wrong frequency', 'Using weight decay as if it were generic regularization magic'], zh: ['把 logits 和概率混为一谈', '在错误频率下 step scheduler', '把 weight decay 当成通用魔法正则项']}, nextStep: { en: 'The next module turns isolated training code into a real data pipeline.', zh: '下一模块会把零散训练代码推进成真正的数据管线。'} },
      { slug: 'data-pipeline-design', order: 5, title: { en: 'Data Pipeline Design', zh: '数据管线设计' }, summary: { en: 'Build datasets and loaders that support real training loops.', zh: '构建能支撑真实训练循环的数据集与加载器。'}, whyItMatters: { en: 'Many model problems are actually data problems: bad labels, wrong normalization, hidden leakage, and slow input pipelines.', zh: '很多所谓模型问题，本质上都是数据问题，比如标签错误、归一化错误、数据泄漏和输入瓶颈。'}, prerequisites: { en: ['PyTorch basics', 'Basic file handling'], zh: ['PyTorch 基础', '基础文件处理']}, objectives: { en: ['Write custom Dataset classes', 'Use transforms and collate_fn intentionally', 'Profile input throughput and worker behavior'], zh: ['编写自定义 Dataset', '有意识地使用 transforms 与 collate_fn', '分析输入吞吐和 worker 行为']}, concepts: { en: ['Dataset vs DataLoader', 'Batching and shuffling', 'Augmentation and leakage'], zh: ['Dataset 与 DataLoader', 'batching 与 shuffle', '数据增强与泄漏']}, practice: { en: ['Create a small image dataset loader', 'Implement train/test transforms', 'Visualize batches before training starts'], zh: ['创建一个小型图像数据加载器', '实现训练/测试变换', '在训练前先可视化 batch']}, output: { en: 'A reusable data pipeline template for later projects.', zh: '一个可在后续项目里复用的数据管线模板。'}, commonMistakes: { en: ['Applying train augmentation to validation data', 'Using too many workers blindly', 'Never inspecting a batch visually'], zh: ['把训练增强错误用于验证集', '盲目使用过多 workers', '从不肉眼检查 batch']}, nextStep: { en: 'With data flowing correctly, it is time to build a training loop worth keeping.', zh: '当数据流正确后，就可以搭建真正可保留的训练循环。'} },
      { slug: 'training-loop-patterns', order: 6, title: { en: 'Training Loop Patterns', zh: '训练循环模式' }, summary: { en: 'Structure a training loop that supports validation, checkpoints, and debugging.', zh: '组织一个支持验证、checkpoint 和调试的训练循环。'}, whyItMatters: { en: 'Messy training code makes reproducibility and debugging nearly impossible.', zh: '混乱的训练代码会让可复现性和调试几乎不可能。'}, prerequisites: { en: ['DataLoader usage', 'Optimizers and losses'], zh: ['DataLoader 使用', '优化器与损失函数']}, objectives: { en: ['Separate train and eval phases clearly', 'Track metrics and checkpoints', 'Organize configs and seeds'], zh: ['清晰拆分训练与评估阶段', '跟踪指标与 checkpoint', '组织配置和随机种子']}, concepts: { en: ['Epoch structure', 'Validation discipline', 'Checkpoint recovery'], zh: ['epoch 结构', '验证纪律', 'checkpoint 恢复']}, practice: { en: ['Refactor a messy script into clear functions', 'Add checkpoint save/load', 'Log train/val accuracy every epoch'], zh: ['把混乱脚本重构成清晰函数', '加入 checkpoint 存取', '每个 epoch 记录训练/验证准确率']}, output: { en: 'A production-style training loop skeleton.', zh: '一个工程化训练循环骨架。'}, commonMistakes: { en: ['Evaluating with model.train()', 'Saving only model weights and losing optimizer state', 'Changing too many variables between runs'], zh: ['在 model.train() 状态下做评估', '只存模型权重而丢掉优化器状态', '每次实验同时改太多变量']}, nextStep: { en: 'Next, make the loop hardware-aware so it can scale beyond CPU.', zh: '下一步是让训练循环具备硬件意识，不再停留在 CPU。'} },
      { slug: 'gpu-acceleration-basics', order: 7, title: { en: 'GPU Acceleration Basics', zh: 'GPU 加速基础' }, summary: { en: 'Write device-aware code and understand transfer costs and throughput.', zh: '写 device-aware 代码，并理解传输成本与吞吐。'}, whyItMatters: { en: 'Hardware awareness is where toy notebooks stop and real ML engineering starts.', zh: '硬件意识正是 toy notebook 和真实 ML 工程的分水岭。'}, prerequisites: { en: ['Training loop patterns', 'Tensor basics'], zh: ['训练循环模式', 'tensor 基础']}, objectives: { en: ['Move models and tensors across devices safely', 'Understand MPS vs CUDA differences', 'Measure speedups and bottlenecks'], zh: ['安全地在设备间迁移模型与 tensor', '理解 MPS 与 CUDA 的差异', '测量加速收益与瓶颈']}, concepts: { en: ['Host-device transfer', 'Pinned memory', 'Throughput vs latency'], zh: ['主机-设备传输', 'pinned memory', '吞吐与延迟']}, practice: { en: ['Benchmark one step on CPU vs GPU', 'Profile dataloader transfer time', 'Test mixed precision support on available hardware'], zh: ['基准测试 CPU 与 GPU 的单步训练', '分析 dataloader 传输耗时', '测试当前硬件上的混合精度支持']}, output: { en: 'A device-agnostic training script with basic timing instrumentation.', zh: '一个带基础计时能力的设备无关训练脚本。'}, commonMistakes: { en: ['Forgetting to move labels to device', 'Synchronizing too often during timing', 'Assuming MPS and CUDA behave identically'], zh: ['忘记把 labels 迁移到 device', '计时时过度同步', '误以为 MPS 与 CUDA 完全一致']}, nextStep: { en: 'Now apply all of this to convolutional models that actually solve vision tasks.', zh: '接下来把这些能力真正应用到卷积模型和视觉任务中。'} },
      { slug: 'convolutional-networks', order: 8, title: { en: 'Convolutional Networks', zh: '卷积神经网络' }, summary: { en: 'Understand receptive fields, conv blocks, and residual design before using ResNet as a black box.', zh: '在把 ResNet 当黑盒前，先理解感受野、卷积 block 与残差设计。'}, whyItMatters: { en: 'CNNs remain one of the clearest ways to learn feature extraction and architecture design.', zh: 'CNN 仍然是学习特征提取与架构设计最清晰的入口之一。'}, prerequisites: { en: ['Training loops', 'GPU basics'], zh: ['训练循环', 'GPU 基础']}, objectives: { en: ['Compute feature map shapes correctly', 'Design conv blocks and residual shortcuts', 'Compare shallow and deep CNNs'], zh: ['正确计算 feature map shape', '设计 conv block 与残差 shortcut', '比较浅层与深层 CNN']}, concepts: { en: ['Convolution and padding', 'Pooling and receptive field growth', 'Residual learning'], zh: ['卷积与 padding', '池化与感受野增长', '残差学习']}, practice: { en: ['Build a CIFAR-style CNN', 'Add residual shortcuts', 'Compare validation accuracy with and without augmentation'], zh: ['构建一个 CIFAR 风格 CNN', '加入残差 shortcut', '比较有无增强时的验证准确率']}, output: { en: 'A CNN baseline and an improved residual version for CIFAR-10.', zh: '一个 CNN baseline 和一个改进后的残差版本。'}, commonMistakes: { en: ['Using ImageNet-style maxpool on tiny 32x32 images', 'Losing track of feature map shapes', 'Overfitting before checking augmentation and regularization'], zh: ['在 32x32 小图上误用 ImageNet 风格 maxpool', '丢失 feature map shape 跟踪', '还没检查增强和正则就先陷入过拟合']}, nextStep: { en: 'This sets up the final capstone, where you assemble the full CNN training pipeline end to end.', zh: '这为最终压轴项目做准备，你将端到端组装完整 CNN 训练管线。'} },
      { slug: 'cnn-capstone-cifar10', order: 9, title: { en: 'Capstone: CIFAR-10 CNN Classifier', zh: '压轴：CIFAR-10 CNN 分类器' }, summary: { en: 'Integrate data, model, optimization, logging, and export into one coherent project.', zh: '把数据、模型、优化、日志与导出整合成一个完整项目。'}, whyItMatters: { en: 'This is where isolated concepts become an engineering workflow you can trust and reuse.', zh: '这一步会把零散概念真正整合成可复用、可相信的工程工作流。'}, prerequisites: { en: ['All previous PyTorch modules'], zh: ['前面全部 PyTorch 模块']}, objectives: { en: ['Train a robust CIFAR-10 classifier', 'Track metrics and analyze errors', 'Export and validate the trained model'], zh: ['训练一个稳定的 CIFAR-10 分类器', '跟踪指标并分析错误', '导出并验证训练好的模型']}, concepts: { en: ['End-to-end training workflow', 'Error analysis', 'Model export and parity checks'], zh: ['端到端训练工作流', '错误分析', '模型导出与一致性检查']}, practice: { en: ['Train to target accuracy', 'Build confusion-matrix analysis', 'Export TorchScript and run parity tests'], zh: ['训练到目标精度', '构建 confusion matrix 分析', '导出 TorchScript 并做一致性测试']}, output: { en: 'A complete image-classification project suitable for portfolio and deployment experiments.', zh: '一个适合作为作品集与部署实验基础的完整图像分类项目。'}, commonMistakes: { en: ['Chasing accuracy before validating the pipeline', 'No baseline comparison', 'Ignoring export correctness'], zh: ['在验证管线前就盲目追精度', '没有 baseline 对比', '忽略导出后的正确性']}, nextStep: { en: 'You are now ready to move into sequence modeling and transformer systems.', zh: '到这里，你已经准备好进入序列建模与 transformer 系统。'} },
    ],
  },
  {
    courseSlug: 'transformer-deep-dive',
    courseTitle: { en: 'Transformer Deep Dive', zh: 'Transformer 深度剖析' },
    intro: { en: 'This track explains modern transformer systems from attention intuition to decoder models, fine-tuning, and architectural tradeoffs.', zh: '这条课程从 attention 直觉出发，一路讲到 decoder 模型、微调方法和现代架构取舍。'},
    modules: [
      { slug: 'why-attention', order: 1, title: { en: 'Why Attention', zh: '为什么需要 Attention' }, summary: { en: 'See why fixed hidden-state sequence models hit a wall.', zh: '理解固定 hidden state 序列模型为什么会撞墙。'}, whyItMatters: { en: 'Without this intuition, attention feels like formula memorization instead of a solution to a real bottleneck.', zh: '如果没有这层直觉，attention 就会像死记公式，而不是在解决真实瓶颈。'}, prerequisites: { en: ['Basic sequence concepts', 'RNN familiarity helps'], zh: ['基础序列概念', '了解 RNN 更好']}, objectives: { en: ['Understand long-context bottlenecks in RNNs', 'Explain direct token-to-token interaction', 'Connect attention to parallel computation'], zh: ['理解 RNN 在长上下文中的瓶颈', '解释 token 间直接交互的价值', '把 attention 和并行计算联系起来']}, concepts: { en: ['Context bottlenecks', 'Parallel sequence modeling', 'Information routing'], zh: ['上下文瓶颈', '并行序列建模', '信息路由']}, practice: { en: ['Compare a toy RNN and attention mechanism on a long dependency example'], zh: ['在长依赖例子上对比 toy RNN 和 attention 机制']}, output: { en: 'A notebook that visually explains why attention scales better.', zh: '一个可视化解释 attention 为什么更可扩展的 notebook。'}, commonMistakes: { en: ['Thinking attention is only about speed', 'Ignoring the memory-computation tradeoff'], zh: ['以为 attention 只是更快', '忽视内存与计算 tradeoff']}, nextStep: { en: 'Now derive the actual attention formula.', zh: '接下来正式推导 attention 公式。'} },
      { slug: 'scaled-dot-product-attention', order: 2, title: { en: 'Scaled Dot-Product Attention', zh: '缩放点积注意力' }, summary: { en: 'Implement the core attention primitive from first principles.', zh: '从第一性原理实现 attention 核心算子。'}, whyItMatters: { en: 'Everything in transformers sits on top of this operation.', zh: 'transformer 的绝大部分机制都建立在这个算子之上。'}, prerequisites: { en: ['Linear algebra basics'], zh: ['线性代数基础']}, objectives: { en: ['Interpret Q, K, and V operationally', 'Explain scaling and masking', 'Implement attention in plain PyTorch'], zh: ['从操作层面理解 Q、K、V', '解释缩放和 mask', '用原生 PyTorch 实现 attention']}, concepts: { en: ['Queries, keys, values', 'Masking', 'Softmax weighting'], zh: ['query、key、value', 'mask 机制', 'softmax 加权']}, practice: { en: ['Write a tested single-head attention function'], zh: ['写一个带测试的单头 attention 函数']}, output: { en: 'A reusable attention primitive with shape assertions.', zh: '一个带 shape 断言的可复用 attention 原语。'}, commonMistakes: { en: ['Forgetting scale by sqrt(d)', 'Applying mask after softmax', 'Losing track of dimensions'], zh: ['忘记除以 sqrt(d)', '在 softmax 后才加 mask', '丢失维度追踪']}, nextStep: { en: 'Then expand one head into many and understand why that helps.', zh: '接着把单头扩展成多头，并理解这样做的价值。'} },
      { slug: 'multi-head-attention', order: 3, title: { en: 'Multi-Head Attention', zh: '多头注意力' }, summary: { en: 'Split representation space into multiple attention subspaces.', zh: '把表示空间拆成多个 attention 子空间。'}, whyItMatters: { en: 'Multi-head attention is where representational diversity enters the transformer block.', zh: '多头注意力是 transformer block 获得表征多样性的关键。'}, prerequisites: { en: ['Single-head attention'], zh: ['单头 attention']}, objectives: { en: ['Reshape tensors for heads safely', 'Understand head dimension vs model dimension', 'Inspect parameter and compute costs'], zh: ['安全地为多头重排 tensor', '理解 head dimension 与 model dimension 的关系', '检查参数量与计算成本']}, concepts: { en: ['Projection matrices', 'Head concatenation', 'Per-head specialization'], zh: ['投影矩阵', '多头拼接', '每头专门化']}, practice: { en: ['Implement a minimal multi-head attention module'], zh: ['实现一个最小多头注意力模块']}, output: { en: 'A working multi-head attention class with shape tracing.', zh: '一个带 shape 跟踪的可运行多头注意力类。'}, commonMistakes: { en: ['Incorrect transpose order', 'Mismatched head dimensions', 'Using view instead of reshape carelessly'], zh: ['transpose 顺序错误', 'head 维度不匹配', '不小心误用 view']}, nextStep: { en: 'The model still lacks order, so next comes positional information.', zh: '模型仍然缺少顺序信息，下一步就是位置编码。'} },
      { slug: 'positional-encoding', order: 4, title: { en: 'Positional Encoding and RoPE', zh: '位置编码与 RoPE' }, summary: { en: 'Restore sequence order in an otherwise permutation-invariant architecture.', zh: '给本来不感知顺序的架构补回位置信息。'}, whyItMatters: { en: 'Without positional information, a transformer sees a bag of tokens, not a sequence.', zh: '没有位置信息，transformer 看到的只是 token 集合，而不是序列。'}, prerequisites: { en: ['Attention basics'], zh: ['attention 基础']}, objectives: { en: ['Compare sinusoidal, learned, and rotary methods', 'Understand extrapolation tradeoffs', 'See why RoPE became common in modern LLMs'], zh: ['比较 sinusoidal、learned 和 rotary 方法', '理解外推能力差异', '理解 RoPE 为什么在现代 LLM 中流行']}, concepts: { en: ['Absolute vs relative positions', 'Rotary embeddings', 'Sequence length extrapolation'], zh: ['绝对位置与相对位置', 'rotary embedding', '序列长度外推']}, practice: { en: ['Visualize sinusoidal encodings and compare on a toy task'], zh: ['可视化 sinusoidal 编码并在 toy task 上对比']}, output: { en: 'A short report comparing positional schemes.', zh: '一份比较不同位置编码方案的简报。'}, commonMistakes: { en: ['Treating all positional schemes as equivalent', 'Ignoring long-context effects'], zh: ['把所有位置方案都当成等价', '忽视长上下文影响']}, nextStep: { en: 'Now assemble these pieces into a full transformer block.', zh: '接着把这些部分组装成完整 transformer block。'} },
      { slug: 'transformer-block-anatomy', order: 5, title: { en: 'Transformer Block Anatomy', zh: 'Transformer Block 解剖' }, summary: { en: 'Understand residuals, norms, and feed-forward layers as one optimization unit.', zh: '把残差、归一化和前馈网络看成一个整体优化单元。'}, whyItMatters: { en: 'Most transformer engineering is really about making deep residual stacks train reliably.', zh: '大量 transformer 工程问题，本质上都是如何让深残差堆叠稳定训练。'}, prerequisites: { en: ['Multi-head attention'], zh: ['多头注意力']}, objectives: { en: ['Explain pre-norm vs post-norm', 'Understand FFN width and capacity', 'Assemble a minimal block'], zh: ['解释 pre-norm 与 post-norm', '理解 FFN 宽度与容量', '组装最小 transformer block']}, concepts: { en: ['Residual paths', 'LayerNorm placement', 'Feed-forward expansion'], zh: ['残差路径', 'LayerNorm 放置位置', '前馈扩展层']}, practice: { en: ['Build a transformer block and test on fake data'], zh: ['构建 transformer block 并在假数据上测试']}, output: { en: 'A reusable transformer block implementation.', zh: '一个可复用的 transformer block 实现。'}, commonMistakes: { en: ['Wrong residual ordering', 'Ignoring normalization placement', 'Underestimating FFN compute'], zh: ['残差顺序错误', '忽略归一化放置位置', '低估 FFN 计算量']}, nextStep: { en: 'Next distinguish encoder and decoder reasoning patterns.', zh: '下一步区分 encoder 和 decoder 的思维方式。'} },
      { slug: 'encoder-models', order: 6, title: { en: 'Encoder Models and BERT Thinking', zh: 'Encoder 模型与 BERT 思维' }, summary: { en: 'Learn bidirectional contextual encoding for classification and retrieval.', zh: '学习面向分类与检索的双向上下文编码。'}, whyItMatters: { en: 'Encoder models solve a different problem from generative decoder models.', zh: 'encoder 模型解决的问题，与生成式 decoder 模型并不相同。'}, prerequisites: { en: ['Transformer block'], zh: ['transformer block']}, objectives: { en: ['Explain masked language modeling', 'Use CLS-style classification heads', 'Compare pooled vs token-level outputs'], zh: ['解释 masked language modeling', '使用 CLS 风格分类头', '比较 pooled 与 token-level 输出']}, concepts: { en: ['Bidirectional context', 'Masked objectives', 'Sentence representations'], zh: ['双向上下文', 'mask 目标', '句子表示']}, practice: { en: ['Train a tiny masked-token encoder on toy data'], zh: ['在 toy 数据上训练一个小型 masked-token encoder']}, output: { en: 'A minimal BERT-style experiment.', zh: '一个最小 BERT 风格实验。'}, commonMistakes: { en: ['Assuming encoder and decoder pretraining are interchangeable'], zh: ['误以为 encoder 与 decoder 预训练是可互换的']}, nextStep: { en: 'Then flip to causal generation with decoder-only models.', zh: '接着切换到 decoder-only 的因果生成模型。'} },
      { slug: 'decoder-models', order: 7, title: { en: 'Decoder Models and GPT Thinking', zh: 'Decoder 模型与 GPT 思维' }, summary: { en: 'Build causal next-token predictors that generate text autoregressively.', zh: '构建因果 next-token 预测器，做自回归文本生成。'}, whyItMatters: { en: 'Modern LLM systems are largely decoder-first, so this mental model matters enormously.', zh: '现代 LLM 系统大多以 decoder 为中心，所以这套思维方式非常关键。'}, prerequisites: { en: ['Attention and masking'], zh: ['attention 与 masking']}, objectives: { en: ['Understand causal masks', 'Train tiny autoregressive models', 'Interpret sampling behavior'], zh: ['理解 causal mask', '训练小型自回归模型', '解释采样行为']}, concepts: { en: ['Next-token prediction', 'Autoregressive generation', 'KV caching basics'], zh: ['next-token prediction', '自回归生成', 'KV cache 基础']}, practice: { en: ['Train a tiny character-level decoder and sample outputs'], zh: ['训练一个字符级小 decoder 并采样输出']}, output: { en: 'A small GPT-style model that generates toy text.', zh: '一个能生成 toy 文本的小型 GPT 风格模型。'}, commonMistakes: { en: ['Masking errors that silently leak future tokens', 'Judging model quality from one sample only'], zh: ['mask 错误导致未来 token 泄漏', '只凭一个 sample 判断模型质量']}, nextStep: { en: 'Next comes the training recipe that turns toy models into stable runs.', zh: '下一步是让 toy 模型变成稳定训练的工程配方。'} },
      { slug: 'training-recipes', order: 8, title: { en: 'Training Recipes That Work', zh: '真正有效的训练配方' }, summary: { en: 'Learn warmup, clipping, precision, and data choices that stabilize transformer training.', zh: '掌握能稳定 transformer 训练的 warmup、裁剪、精度和数据策略。'}, whyItMatters: { en: 'Most failed transformer training runs are recipe failures, not idea failures.', zh: '大多数 transformer 训练失败，问题不在想法，而在训练配方。'}, prerequisites: { en: ['Optimizer basics'], zh: ['优化器基础']}, objectives: { en: ['Choose learning rates and warmup', 'Use clipping and mixed precision carefully', 'Match model size to hardware budget'], zh: ['选择学习率与 warmup', '谨慎使用裁剪与混合精度', '把模型大小匹配到硬件预算']}, concepts: { en: ['Warmup', 'Gradient clipping', 'Sequence length vs batch tradeoff'], zh: ['warmup', '梯度裁剪', '序列长度与 batch 大小权衡']}, practice: { en: ['Compare runs with and without warmup on a small decoder'], zh: ['对比小型 decoder 有无 warmup 的训练表现']}, output: { en: 'A short training-stability benchmark note.', zh: '一份训练稳定性 benchmark 记录。'}, commonMistakes: { en: ['No warmup on fragile runs', 'Treating OOM as random bad luck', 'Ignoring sequence-length cost'], zh: ['在脆弱训练上不做 warmup', '把 OOM 当成随机倒霉', '忽略序列长度成本']}, nextStep: { en: 'Then learn how to adapt pretrained models efficiently.', zh: '然后学习如何高效适配预训练模型。'} },
      { slug: 'fine-tuning-peft', order: 9, title: { en: 'Fine-tuning and PEFT', zh: '微调与 PEFT' }, summary: { en: 'Adapt pretrained models with full fine-tuning or parameter-efficient methods like LoRA.', zh: '用完整微调或 LoRA 等参数高效方法适配预训练模型。'}, whyItMatters: { en: 'In practice, most teams adapt models rather than pretrain from scratch.', zh: '在现实中，大多数团队做的是模型适配，而不是从零预训练。'}, prerequisites: { en: ['Pretrained model basics'], zh: ['预训练模型基础']}, objectives: { en: ['Compare full fine-tuning and LoRA', 'Understand rank and target-module choice', 'Evaluate adaptation quality fairly'], zh: ['比较完整微调与 LoRA', '理解 rank 与 target module 选择', '公平评估适配质量']}, concepts: { en: ['PEFT', 'LoRA rank', 'Task adaptation'], zh: ['PEFT', 'LoRA rank', '任务适配']}, practice: { en: ['Apply LoRA to a small transformer classifier'], zh: ['把 LoRA 应用于小型 transformer 分类器']}, output: { en: 'A fair comparison between full tuning and PEFT.', zh: '一份完整微调与 PEFT 的公平比较。'}, commonMistakes: { en: ['Treating LoRA as universally effective', 'Ignoring base-model mismatch', 'Comparing runs with different tokenizers or prompts'], zh: ['把 LoRA 当成处处有效的通解', '忽视 base model 不匹配', '在不同 tokenizer 或 prompt 条件下乱比较']}, nextStep: { en: 'Now build a complete mini-GPT to integrate the whole stack.', zh: '接下来构建完整 mini-GPT，把整套知识串起来。'} },
      { slug: 'mini-gpt-capstone', order: 10, title: { en: 'Capstone: Mini-GPT Build', zh: '压轴：Mini-GPT 构建' }, summary: { en: 'Assemble tokenizer, embeddings, blocks, training, and sampling into one working model.', zh: '把 tokenizer、embedding、block、训练和采样整合成一个可运行模型。'}, whyItMatters: { en: 'This is where transformer theory turns into a system you can inspect and trust.', zh: '这一步把 transformer 理论真正变成你可以检查、理解和信任的系统。'}, prerequisites: { en: ['All previous transformer modules'], zh: ['前面全部 transformer 模块']}, objectives: { en: ['Train and sample from a tiny GPT', 'Inspect failure modes', 'Connect architecture, optimization, and generation quality'], zh: ['训练并采样一个小 GPT', '观察失败模式', '把架构、优化和生成质量关联起来']}, concepts: { en: ['End-to-end decoder pipeline', 'Sampling diagnostics', 'Checkpoint analysis'], zh: ['端到端 decoder 管线', '采样诊断', 'checkpoint 分析']}, practice: { en: ['Train on a small text corpus and compare checkpoints'], zh: ['在小语料上训练并比较不同 checkpoint']}, output: { en: 'A working mini-GPT project with training and inference scripts.', zh: '一个带训练和推理脚本的可运行 mini-GPT 项目。'}, commonMistakes: { en: ['Overfitting tiny data and calling it success', 'Ignoring sampling parameters', 'No qualitative evaluation of outputs'], zh: ['在小数据上过拟合却误以为成功', '忽视采样参数', '不做生成结果的定性评估']}, nextStep: { en: 'You are now ready to study modern transformer variants and system-level tradeoffs.', zh: '到这里，你已经可以进入现代 transformer 变体与系统级权衡。'} },
      { slug: 'modern-variants', order: 11, title: { en: 'Modern Transformer Variants', zh: '现代 Transformer 变体' }, summary: { en: 'Map the frontier: Flash Attention, MoE, grouped-query attention, and beyond.', zh: '建立前沿地图：Flash Attention、MoE、GQA 等现代变体。'}, whyItMatters: { en: 'This is the bridge from education to reading current model-system papers with confidence.', zh: '这一模块把学习阶段和真正读懂当前模型系统论文连接起来。'}, prerequisites: { en: ['Mini-GPT capstone'], zh: ['mini-GPT 压轴项目']}, objectives: { en: ['Explain why modern variants exist', 'Compare compute, memory, and quality tradeoffs', 'Read new papers without getting lost in acronyms'], zh: ['解释现代变体为什么出现', '比较计算、内存和质量 tradeoff', '读新论文时不再被缩写劫持']}, concepts: { en: ['Flash Attention', 'MoE', 'Grouped-query attention'], zh: ['Flash Attention', 'MoE', 'Grouped-query attention']}, practice: { en: ['Read one modern architecture paper and summarize the core systems tradeoff'], zh: ['阅读一篇现代架构论文，并总结核心系统 tradeoff']}, output: { en: 'A one-page architecture tradeoff map.', zh: '一页架构 tradeoff 地图。'}, commonMistakes: { en: ['Chasing novelty without understanding the bottleneck addressed', 'Ignoring deployment complexity'], zh: ['只追新名词，不理解其解决的瓶颈', '忽视部署复杂度']}, nextStep: { en: 'From here, you can move into production LLM systems or research implementation.', zh: '从这里你可以走向生产级 LLM 系统或研究实现。'} },
    ],
  },
  {
    courseSlug: 'reinforcement-learning',
    courseTitle: { en: 'Reinforcement Learning', zh: '强化学习' },
    intro: { en: 'This track turns RL from a bag of algorithms into a coherent decision-making framework from MDPs to PPO and engineering workflows.', zh: '这条课程会把 RL 从零散算法拼盘，整理成从 MDP 到 PPO 再到工程工作流的一致决策框架。'},
    modules: [
      { slug: 'mdps-bellman', order: 1, title: { en: 'MDPs and Bellman Equations', zh: 'MDP 与 Bellman 方程' }, summary: { en: 'Learn the formal language that all RL algorithms build on.', zh: '掌握所有 RL 算法共享的形式化语言。'}, whyItMatters: { en: 'Without MDP intuition, RL algorithms feel disconnected and magical.', zh: '没有 MDP 直觉，RL 算法看起来就像一堆互不相干的魔法。'}, prerequisites: { en: ['Basic probability'], zh: ['基础概率']}, objectives: { en: ['Define states, actions, rewards, and returns', 'Interpret Bellman recursion', 'Connect long-horizon decisions to local updates'], zh: ['定义 state、action、reward 与 return', '理解 Bellman 递归', '把长时程决策与局部更新连接起来']}, concepts: { en: ['Return', 'Value function', 'Bellman expectation'], zh: ['return', '价值函数', 'Bellman 期望']}, practice: { en: ['Write Bellman updates by hand on a tiny GridWorld'], zh: ['在小型 GridWorld 上手写 Bellman 更新']}, output: { en: 'A small worksheet that makes Bellman thinking concrete.', zh: '一份把 Bellman 思维具体化的小练习。'}, commonMistakes: { en: ['Confusing reward and return', 'Ignoring discount-factor interpretation'], zh: ['混淆 reward 与 return', '忽视 discount factor 的含义']}, nextStep: { en: 'Now solve small environments exactly with dynamic programming.', zh: '接下来用动态规划精确求解小环境。'} },
      { slug: 'dynamic-programming', order: 2, title: { en: 'Dynamic Programming', zh: '动态规划' }, summary: { en: 'Use exact tabular methods to build value-function intuition.', zh: '用精确表格方法建立价值函数直觉。'}, whyItMatters: { en: 'Dynamic programming makes value updates tangible before function approximation complicates everything.', zh: '在函数逼近把问题复杂化之前，动态规划能让价值更新变得具体可见。'}, prerequisites: { en: ['MDPs'], zh: ['MDP 基础']}, objectives: { en: ['Run policy evaluation', 'Compare policy iteration and value iteration', 'Visualize value improvement'], zh: ['运行策略评估', '比较 policy iteration 和 value iteration', '可视化价值提升']}, concepts: { en: ['Policy evaluation', 'Policy improvement', 'Optimality'], zh: ['策略评估', '策略改进', '最优性']}, practice: { en: ['Implement value iteration for GridWorld'], zh: ['为 GridWorld 实现 value iteration']}, output: { en: 'A tabular solver with policy/value visualization.', zh: '一个带策略与价值可视化的表格求解器。'}, commonMistakes: { en: ['Updating policy before evaluation converges', 'Treating DP as irrelevant because it does not scale'], zh: ['在评估收敛前就急着更新策略', '因为不扩展就误以为 DP 无关紧要']}, nextStep: { en: 'Then shift from exact solutions to sampled returns.', zh: '然后从精确解法切换到采样回报。'} },
      { slug: 'monte-carlo-methods', order: 3, title: { en: 'Monte Carlo Methods', zh: 'Monte Carlo 方法' }, summary: { en: 'Estimate values from full trajectories without bootstrapping.', zh: '在不 bootstrapping 的前提下，从完整轨迹估计价值。'}, whyItMatters: { en: 'Monte Carlo methods reveal the variance side of RL before TD methods step in.', zh: 'Monte Carlo 让你先看到 RL 里的高方差一面，再进入 TD 方法。'}, prerequisites: { en: ['Returns and MDPs'], zh: ['return 与 MDP']}, objectives: { en: ['Compare first-visit and every-visit estimates', 'Understand variance across episodes', 'Connect sampling to unbiased estimation'], zh: ['比较 first-visit 与 every-visit 估计', '理解 episode 之间的方差', '把采样与无偏估计联系起来']}, concepts: { en: ['Episode return', 'Unbiased estimation', 'Variance'], zh: ['episode 回报', '无偏估计', '方差']}, practice: { en: ['Estimate state values from sampled episodes'], zh: ['从采样 episode 估计状态价值']}, output: { en: 'A notebook comparing Monte Carlo estimates across seeds.', zh: '一个比较不同 seed 下 Monte Carlo 估计的 notebook。'}, commonMistakes: { en: ['Expecting low-variance learning from sparse episodic returns'], zh: ['在稀疏 episodic return 上期待低方差学习']}, nextStep: { en: 'Now add bootstrapping and enter the TD family.', zh: '接着加入 bootstrapping，进入 TD 家族。'} },
      { slug: 'temporal-difference-learning', order: 4, title: { en: 'Temporal Difference Learning', zh: '时序差分学习' }, summary: { en: 'Blend sampling and bootstrapping into practical value learning.', zh: '把采样与 bootstrapping 结合成更实用的价值学习。'}, whyItMatters: { en: 'TD methods sit at the center of classic RL and explain why bootstrapping changes stability and speed.', zh: 'TD 方法处在经典 RL 中心位置，也解释了 bootstrapping 如何改变稳定性与速度。'}, prerequisites: { en: ['Monte Carlo basics'], zh: ['Monte Carlo 基础']}, objectives: { en: ['Compare TD(0), SARSA, and Q-learning', 'Understand bootstrap targets', 'Reason about on-policy vs off-policy'], zh: ['比较 TD(0)、SARSA 与 Q-learning', '理解 bootstrap target', '推理 on-policy 与 off-policy 差异']}, concepts: { en: ['Bootstrapping', 'TD target', 'On-policy vs off-policy'], zh: ['bootstrapping', 'TD target', 'on-policy 与 off-policy']}, practice: { en: ['Train SARSA and Q-learning on Taxi-v3'], zh: ['在 Taxi-v3 上训练 SARSA 与 Q-learning']}, output: { en: 'A comparison of learning curves and policy behavior.', zh: '一份对比学习曲线与策略行为的记录。'}, commonMistakes: { en: ['Not handling terminal states correctly', 'Mixing policy used for acting and updating'], zh: ['终止状态处理错误', '把行动策略和更新策略混在一起']}, nextStep: { en: 'Then replace tables with neural approximators through DQN.', zh: '然后用神经网络逼近器取代表格方法，进入 DQN。'} },
      { slug: 'deep-q-networks', order: 5, title: { en: 'Deep Q-Networks', zh: '深度 Q 网络' }, summary: { en: 'Move from tabular value learning to neural function approximation.', zh: '从表格价值学习走向神经网络函数逼近。'}, whyItMatters: { en: 'DQN is the point where RL becomes modern deep RL engineering.', zh: 'DQN 是 RL 真正走向现代深度强化学习工程的转折点。'}, prerequisites: { en: ['TD learning', 'PyTorch basics'], zh: ['TD 学习', 'PyTorch 基础']}, objectives: { en: ['Understand replay buffers and target networks', 'Train a neural Q-function', 'Diagnose unstable value estimates'], zh: ['理解 replay buffer 与 target network', '训练神经 Q 函数', '诊断不稳定的价值估计']}, concepts: { en: ['Replay', 'Target network', 'Q-value estimation'], zh: ['经验回放', '目标网络', 'Q 值估计']}, practice: { en: ['Train DQN on CartPole or Pong-lite'], zh: ['在 CartPole 或简化 Pong 上训练 DQN']}, output: { en: 'A scratch DQN baseline with reward curves.', zh: '一个带 reward 曲线的 DQN baseline。'}, commonMistakes: { en: ['Using correlated online samples only', 'No target network', 'Over-interpreting one lucky run'], zh: ['只用相关性极强的在线样本', '没有 target network', '过度解读一次幸运训练']}, nextStep: { en: 'After value-based deep RL, switch to direct policy optimization.', zh: '在价值型深度 RL 之后，进入直接策略优化。'} },
      { slug: 'policy-gradients', order: 6, title: { en: 'Policy Gradients and REINFORCE', zh: '策略梯度与 REINFORCE' }, summary: { en: 'Optimize policies directly and feel the pain of variance firsthand.', zh: '直接优化策略，并亲身感受高方差问题。'}, whyItMatters: { en: 'Policy gradients open the door to continuous control and modern actor-critic methods.', zh: '策略梯度打开了连续控制和现代 actor-critic 方法的大门。'}, prerequisites: { en: ['Probability basics', 'MDP intuition'], zh: ['概率基础', 'MDP 直觉']}, objectives: { en: ['Derive the score-function estimator', 'Understand baseline variance reduction', 'Train REINFORCE on a simple environment'], zh: ['推导 score-function estimator', '理解 baseline 降方差', '在简单环境上训练 REINFORCE']}, concepts: { en: ['Log-derivative trick', 'Return-weighted gradients', 'Variance reduction'], zh: ['log-derivative trick', 'return 加权梯度', '方差降低']}, practice: { en: ['Train REINFORCE with and without baseline'], zh: ['分别训练有无 baseline 的 REINFORCE']}, output: { en: 'A small experiment showing why variance reduction matters.', zh: '一个展示方差降低为何关键的小实验。'}, commonMistakes: { en: ['Assuming policy gradients are automatically stable', 'Ignoring reward scaling'], zh: ['以为策略梯度天然稳定', '忽视 reward scaling']}, nextStep: { en: 'Now add a critic and move into actor-critic systems.', zh: '接着加入 critic，进入 actor-critic 系统。'} },
      { slug: 'actor-critic', order: 7, title: { en: 'Actor-Critic Methods', zh: 'Actor-Critic 方法' }, summary: { en: 'Combine policy learning with value estimation for lower-variance updates.', zh: '把策略学习与价值估计结合，获得更低方差更新。'}, whyItMatters: { en: 'Most practical modern RL relies on actor-critic structure in one form or another.', zh: '大多数现代实用 RL 方法，本质上都依赖 actor-critic 结构。'}, prerequisites: { en: ['Policy gradients', 'Value functions'], zh: ['策略梯度', '价值函数']}, objectives: { en: ['Explain the actor/critic split', 'Use advantage estimates', 'Implement a simple A2C-style loop'], zh: ['解释 actor/critic 分工', '使用 advantage 估计', '实现简单的 A2C 风格循环']}, concepts: { en: ['Critic targets', 'Advantages', 'Bias-variance balance'], zh: ['critic target', 'advantage', 'bias-variance 平衡']}, practice: { en: ['Train a small actor-critic baseline'], zh: ['训练一个小型 actor-critic baseline']}, output: { en: 'An actor-critic implementation with tracked policy/value losses.', zh: '一个带策略损失与价值损失跟踪的 actor-critic 实现。'}, commonMistakes: { en: ['Using noisy critic targets carelessly', 'Confusing value and advantage'], zh: ['粗心使用噪声很大的 critic target', '混淆 value 与 advantage']}, nextStep: { en: 'Then move to PPO, the workhorse practical policy optimizer.', zh: '然后进入 PPO，这个实用策略优化的主力算法。'} },
      { slug: 'ppo', order: 8, title: { en: 'Proximal Policy Optimization', zh: '近端策略优化 PPO' }, summary: { en: 'Learn the clipped-objective method that dominates practical policy optimization.', zh: '掌握主导实践的 clipped objective 策略优化方法。'}, whyItMatters: { en: 'PPO is one of the most common bridges from RL theory to real training systems.', zh: 'PPO 是从 RL 理论走向真实训练系统最常见的桥梁之一。'}, prerequisites: { en: ['Actor-critic basics'], zh: ['actor-critic 基础']}, objectives: { en: ['Understand clipping and trust-region intuition', 'Use GAE', 'Tune rollout and minibatch settings'], zh: ['理解 clipping 与 trust-region 直觉', '使用 GAE', '调节 rollout 与 minibatch 设置']}, concepts: { en: ['Clipped surrogate objective', 'Entropy bonus', 'GAE'], zh: ['clipped surrogate objective', 'entropy bonus', 'GAE']}, practice: { en: ['Build and train a PPO loop on continuous control'], zh: ['在连续控制上构建并训练 PPO 循环']}, output: { en: 'A PPO trainer with rollout diagnostics.', zh: '一个带 rollout 诊断信息的 PPO trainer。'}, commonMistakes: { en: ['Too many epochs per batch', 'No observation normalization', 'Treating entropy bonus as decoration'], zh: ['每批数据训练 epoch 过多', '没有 observation normalization', '把 entropy bonus 当摆设']}, nextStep: { en: 'Next you will turn scratch algorithms into reproducible engineering workflows.', zh: '接下来把手写算法推进成可复现实验工作流。'} },
      { slug: 'tianshou-engineering', order: 9, title: { en: 'RL Engineering with Tianshou', zh: '用 Tianshou 做 RL 工程化' }, summary: { en: 'Use a real RL library without losing conceptual clarity.', zh: '在不丢失概念清晰度的前提下，使用真正的 RL 库。'}, whyItMatters: { en: 'At some point you need reproducible experiment tooling, not just scratch notebooks.', zh: '走到一定阶段后，你需要的是可复现实验工具，而不再只是手写 notebook。'}, prerequisites: { en: ['Scratch PPO or DQN experience'], zh: ['有手写 PPO 或 DQN 经验']}, objectives: { en: ['Understand policy, collector, buffer, and trainer abstractions', 'Map scratch concepts to library components', 'Run seeded experiments cleanly'], zh: ['理解 policy、collector、buffer 和 trainer 抽象', '把手写概念映射到库组件', '干净地运行多 seed 实验']}, concepts: { en: ['Collector', 'Replay buffer APIs', 'Experiment abstraction'], zh: ['collector', 'replay buffer API', '实验抽象']}, practice: { en: ['Rebuild a previous algorithm using Tianshou'], zh: ['用 Tianshou 重建之前手写过的算法']}, output: { en: 'A reproducible RL experiment pipeline.', zh: '一个可复现的 RL 实验流水线。'}, commonMistakes: { en: ['Using library abstractions without knowing what they hide', 'Failing to align config with scratch baselines'], zh: ['在不理解抽象的前提下直接用库', '配置与手写 baseline 不对齐']}, nextStep: { en: 'Finally, package a full project and compare scratch vs library systems.', zh: '最后打包完整项目，并比较手写与库系统。'} },
      { slug: 'cartpole-project', order: 10, title: { en: 'CartPole Pipeline Project', zh: 'CartPole 流水线项目' }, summary: { en: 'Build a clean RL project pipeline with configs, logging, and evaluation.', zh: '搭建带配置、日志和评估的干净 RL 项目流水线。'}, whyItMatters: { en: 'Project organization is what makes your RL work reproducible and portfolio-ready.', zh: '项目组织能力决定了你的 RL 工作是否可复现、是否能进入作品集。'}, prerequisites: { en: ['Tianshou basics'], zh: ['Tianshou 基础']}, objectives: { en: ['Package training and evaluation scripts', 'Log metrics cleanly', 'Compare seeds and checkpoints'], zh: ['打包训练与评估脚本', '清晰记录指标', '比较 seed 与 checkpoint']}, concepts: { en: ['Experiment packaging', 'Evaluation discipline', 'Checkpoint strategy'], zh: ['实验打包', '评估纪律', 'checkpoint 策略']}, practice: { en: ['Package a CartPole agent as a reusable project template'], zh: ['把 CartPole 智能体打包成可复用项目模板']}, output: { en: 'A reusable RL project skeleton.', zh: '一个可复用的 RL 项目骨架。'}, commonMistakes: { en: ['No fixed config snapshots', 'No evaluation-only mode', 'Mixing environment versions'], zh: ['没有固定配置快照', '没有单独评估模式', '混用环境版本']}, nextStep: { en: 'The final capstone pushes this into a harder continuous-control setting.', zh: '最终压轴项目会把这套能力推向更难的连续控制场景。'} },
      { slug: 'ppo-mujoco-capstone', order: 11, title: { en: 'Capstone: PPO on MuJoCo', zh: '压轴：MuJoCo 上的 PPO' }, summary: { en: 'Apply everything on a harder continuous-control benchmark.', zh: '把所有内容带到更难的连续控制基准上。'}, whyItMatters: { en: 'This is where RL theory, training discipline, and engineering judgment all collide.', zh: '这一步是 RL 理论、训练纪律和工程判断真正碰撞到一起的地方。'}, prerequisites: { en: ['All previous RL modules'], zh: ['前面全部 RL 模块']}, objectives: { en: ['Train a PPO agent on MuJoCo', 'Analyze reward curves and instability', 'Compare scratch and library implementations'], zh: ['在 MuJoCo 上训练 PPO 智能体', '分析 reward 曲线与不稳定性', '比较手写与库实现']}, concepts: { en: ['Continuous control', 'Reward scaling', 'Training instability analysis'], zh: ['连续控制', 'reward scaling', '训练不稳定性分析']}, practice: { en: ['Train HalfCheetah-v4 or a similar environment and write a capstone report'], zh: ['训练 HalfCheetah-v4 或类似环境，并撰写压轴报告']}, output: { en: 'A full PPO continuous-control project and analysis report.', zh: '一个完整 PPO 连续控制项目和分析报告。'}, commonMistakes: { en: ['Jumping to MuJoCo before mastering small environments', 'Trusting one reward curve', 'Ignoring normalization and reward scale'], zh: ['在没掌握小环境前就跳到 MuJoCo', '只相信一条 reward 曲线', '忽视归一化和 reward scale']}, nextStep: { en: 'From here, you can move into advanced RL research, alignment, or agentic decision systems.', zh: '到这里，你可以进入高级 RL 研究、对齐问题或 agent 决策系统。'} },
    ],
  },
];

export function getCourseModules(courseSlug: string) {
  return COURSE_MODULES.find((course) => course.courseSlug === courseSlug);
}

export function getModuleLesson(courseSlug: string, moduleSlug: string) {
  const course = getCourseModules(courseSlug);
  if (!course) return null;
  const module = course.modules.find((item) => item.slug === moduleSlug);
  if (!module) return null;
  return { course, module };
}
