import type { Metadata } from 'next';
import Link from 'next/link';
import { BilingualText } from '@/components/common/BilingualText';

export const metadata: Metadata = {
  title: 'Optimization Concepts',
  description: 'Bilingual overview of important concepts in model optimization and reinforcement learning.',
};

const CONCEPTS = [
  {
    en: { title: 'Reward design', body: 'In RL and agent systems, reward design determines what the system actually optimizes, not what you hope it optimizes. A bad reward creates loophole exploitation, misalignment, and brittle behavior. This is why evaluation and reward shaping are design problems, not post-processing details.' },
    zh: { title: 'Reward design', body: '在 RL 和 agent 系统里，reward design 决定系统真正优化的目标，而不是你以为它在优化什么。奖励设计不好，就会出现钻漏洞、错位优化和脆弱行为。所以评测和 reward shaping 本质上是设计问题，不是后处理细节。' },
  },
  {
    en: { title: 'Credit assignment', body: 'Credit assignment asks which earlier decisions deserve praise or blame for a later outcome. Long-horizon tasks are hard because the useful signal is delayed and noisy. This problem appears not only in RL, but also in long agent workflows and multistep tool use.' },
    zh: { title: 'Credit assignment', body: 'credit assignment 关注的是，最终结果出现后，应该把功劳或责任分配给前面的哪一步决策。长时程任务之所以难，就是因为有效信号又晚又噪。这不只出现在 RL，也出现在长链路 agent 工作流和多步工具调用里。' },
  },
  {
    en: { title: 'Exploration vs exploitation', body: 'A system must choose between using what already seems best and exploring actions that may become better later. Too much exploitation traps the agent in local behavior. Too much exploration wastes time and creates instability. The right balance depends on environment cost, uncertainty, and feedback speed.' },
    zh: { title: '探索与利用', body: '系统必须在“使用当前看起来最优的策略”和“探索未来可能更好的选择”之间取舍。过度利用会让智能体陷入局部行为，过度探索又会浪费时间并制造不稳定。这个平衡取决于环境成本、不确定性和反馈速度。' },
  },
  {
    en: { title: 'Policy optimization', body: 'Policy optimization means improving the action-selection rule directly. In practice this leads to methods like policy gradients and PPO. The hard part is not just moving uphill on reward, but moving in a way that keeps learning stable.' },
    zh: { title: '策略优化', body: '策略优化就是直接改进动作选择规则。实践中这会走向策略梯度和 PPO 这类方法。难点不只是朝着更高 reward 前进，而是要以稳定的方式前进。' },
  },
  {
    en: { title: 'Off-policy vs on-policy', body: 'On-policy methods learn from data generated by the current policy. Off-policy methods can learn from older or different behavior data. Off-policy learning is often more sample-efficient, but it introduces distribution mismatch and stability problems.' },
    zh: { title: 'Off-policy 与 On-policy', body: 'on-policy 方法主要从当前策略生成的数据中学习；off-policy 方法可以利用旧策略甚至其他策略收集的数据。off-policy 往往更省样本，但会带来分布不匹配和稳定性问题。' },
  },
  {
    en: { title: 'Trajectory optimization', body: 'Trajectory optimization looks at sequences of actions as structured plans rather than isolated decisions. This matters in robotics, control, long-horizon RL, and advanced agent planning, where the quality of the full path matters more than one local step.' },
    zh: { title: '轨迹优化', body: '轨迹优化把动作序列当作结构化计划，而不是彼此孤立的单步决策。这在机器人、控制、长时程 RL 和高级 agent planning 中非常重要，因为真正关键的是整条路径质量，而不是某一个局部动作。' },
  },
  {
    en: { title: 'Environment interaction', body: 'Learning systems do not just consume static datasets. In RL and agent systems they act, observe, and adapt through environment interaction. That means latency, simulation fidelity, reset logic, tool reliability, and observation design all become part of the learning problem.' },
    zh: { title: '环境交互', body: '学习系统并不总是只消费静态数据。在 RL 和 agent 系统中，它们会通过环境交互来行动、观察、再适应。这意味着延迟、模拟精度、reset 逻辑、工具可靠性和观察设计都会变成学习问题的一部分。' },
  },
];

export default function OptimizationConceptsPage() {
  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-16">
      <nav className="text-sm text-[var(--text-muted)] mb-8">
        <Link href="/" className="hover:text-[var(--text-primary)]"><BilingualText en="Home" zh="首页" /></Link>
        <span className="mx-2">/</span>
        <span className="text-[var(--text-primary)]"><BilingualText en="Optimization Concepts" zh="优化概念" /></span>
      </nav>

      <h1 className="text-4xl font-extrabold text-[var(--text-primary)] mb-4">
        <BilingualText en="Important Optimization Concepts" zh="模型训练优化的重要概念" />
      </h1>
      <p className="text-[var(--text-muted)] mb-10 max-w-3xl">
        <BilingualText
          en="These concepts matter whenever a learning system must improve through feedback, delayed outcomes, or repeated interaction. They sit at the heart of RL, post-training, and agent decision systems."
          zh="这些概念在学习系统需要通过反馈、延迟结果或反复交互来改进时都非常关键。它们处在 RL、post-training 和 agent 决策系统的核心位置。"
        />
      </p>

      <div className="space-y-4">
        {CONCEPTS.map((item) => (
          <div key={item.en.title} className="card">
            <h2 className="text-xl font-bold text-[var(--text-primary)] mb-3"><BilingualText en={item.en.title} zh={item.zh.title} /></h2>
            <p className="text-sm text-[var(--text-muted)] leading-relaxed"><BilingualText en={item.en.body} zh={item.zh.body} /></p>
          </div>
        ))}
      </div>
    </div>
  );
}
